# remote_theme: lewismiddleton/minima-cayman （minima dark）
# remote_theme: lewismiddleton/cayman-dark
# theme: minima
# theme: jekyll-theme-cayman

remote_theme: wchenyi/cayman
plugins:
- jekyll-remote-theme
  
title: 翻墙小道
description: 尽可能详全面的搜集科学上网信息进行交流学习-非盈利<br>严禁用于违法行为

show_downloads: "true"

github.is_project_page: "true"

github:
   Android: https://wangcy.tk/wall/assets/Android
   Windows: https://wangcy.tk/wall/assets/Windows
  another_url: Wangcy
